
const TOPICS = {
  "convex-control": { label: "Convex Optimization & Control", color: "#2f6fed", x: 300,  y: 420 },
  "acceleration":   { label: "Acceleration & ODEs",           color: "#ff7a18", x: 820,  y: 240 },
  "highdim":        { label: "High-Dimensional Statistics",   color: "#9b6bf3", x: 1230, y: 430 },
  "dynamics":       { label: "Training Dynamics",             color: "#19c2c2", x: 700,  y: 700 },
  "lr-control":     { label: "Learning-Rate Control",         color: "#e0b53d", x: 1080, y: 800 },
  "statistics":     { label: "Statistics",                    color: "#e05c7a", x: 1750, y: 300 },
  "learning-theory":{ label: "Statistical Learning Theory",   color: "#5ad07a", x: 1780, y: 950 },
  "probabilistic":  { label: "Probabilistic ML & Causality",  color: "#c98ae0", x: 2280, y: 500 },
  "deep-learning":  { label: "Deep Learning",                 color: "#ff5c5c", x: 2350, y: 1100 },
  "rl":             { label: "Reinforcement Learning",        color: "#58b8ff", x: 1700, y: 1450 },
  "classic-ai":     { label: "Classic AI",                    color: "#d9a05b", x: 2350, y: 1650 },
  "systems":        { label: "Systems & Computing",           color: "#8fa3bf", x: 300,  y: 1250 },
  "networks":       { label: "Networks & Complexity",         color: "#5adbd0", x: 850,  y: 1250 },
  "society":        { label: "AI & Society",                  color: "#f0c04a", x: 1250, y: 1650 },
  "educators":      { label: "Educators & Explainers",        color: "#a8b86a", x: 380,  y: 1700 },
  "hci":            { label: "HCI & Computing Education",     color: "#e08ab8", x: 900,  y: 1780 },
  "math":           { label: "Mathematics & Theory",          color: "#b58a5f", x: 2750, y: 250 },
};

const PEOPLE = [
  { id: "boyd", name: "Stephen Boyd", affil: "Stanford EE", topic: "convex-control", x: 300, y: 380,
    why: "The control-optimization bridge in person. LMI book (1994), Convex Optimization (2004), CVXPY. Watch: EE364a." },
  { id: "lessard", name: "Laurent Lessard", affil: "Northeastern", topic: "convex-control", x: 430, y: 500,
    why: "First author of the IQC landmark - optimizers analyzed as robust control." },
  { id: "packard", name: "Andrew Packard", affil: "Berkeley ME", topic: "convex-control", x: 350, y: 600,
    why: "Robust-control lineage on the IQC paper." },
  { id: "bertsekas", name: "Dimitri Bertsekas", affil: "MIT / ASU", topic: "convex-control",
    why: "Dynamic programming and optimal control, the textbooks. The control-optimization canon." },
  { id: "recht", name: "Ben Recht", affil: "Berkeley EECS", topic: "acceleration", x: 620, y: 400,
    why: "The connective tissue: IQCs, Lyapunov momentum, matrix completion. argmin essays = the on-ramp." },
  { id: "jordan", name: "Michael I. Jordan", affil: "Berkeley", topic: "acceleration", x: 780, y: 360,
    why: "Lyapunov + variational views of acceleration; the learning-theory gravity well." },
  { id: "wilson", name: "Ashia Wilson", affil: "MIT", topic: "acceleration", x: 920, y: 280,
    why: "Lyapunov analysis of momentum methods - the proofs unified." },
  { id: "wibisono", name: "Andre Wibisono", affil: "Yale", topic: "acceleration", x: 940, y: 160,
    why: "The variational (Bregman-Lagrangian) view: acceleration from an action principle." },
  { id: "su", name: "Weijie Su", affil: "UPenn Wharton", topic: "acceleration", x: 760, y: 140,
    why: "First author of the Nesterov-ODE paper - the optimizer as a damped oscillator." },
  { id: "candes", name: "Emmanuel Candès", affil: "Stanford Math/Stats", topic: "highdim", x: 1100, y: 360,
    why: "Compressed sensing, matrix completion, robust PCA, conformal prediction - applied questions turned into clean math with guarantees." },
  { id: "tao", name: "Terence Tao", affil: "UCLA", topic: "highdim", x: 1330, y: 400,
    why: "Compressed sensing co-author; the pure-math anchor of the map." },
  { id: "donoho", name: "David Donoho", affil: "Stanford", topic: "highdim",
    why: "Wavelets, compressed sensing, curvelets with Candès; '50 Years of Data Science.'" },
  { id: "cohen", name: "Jeremy Cohen", affil: "CMU", topic: "dynamics", x: 620, y: 740,
    why: "First author of edge of stability - the open problem at the heart of modern training dynamics." },
  { id: "kolter", name: "Zico Kolter", affil: "CMU", topic: "dynamics", x: 780, y: 800,
    why: "Edge of stability; robustness and implicit layers beyond it." },
  { id: "talwalkar", name: "Ameet Talwalkar", affil: "CMU", topic: "dynamics", x: 870, y: 700,
    why: "Edge of stability; AutoML angle." },
  { id: "smith", name: "Leslie N. Smith", affil: "U.S. Naval Research Laboratory", topic: "lr-control", x: 1080, y: 820,
    why: "Cyclical learning rates, the LR range test, super-convergence. (The name collides with several academics - hence the affiliation.)" },

  { id: "efron", name: "Bradley Efron", affil: "Stanford", topic: "statistics",
    why: "The bootstrap; Computer Age Statistical Inference with Hastie." },
  { id: "tibshirani", name: "Robert Tibshirani", affil: "Stanford", topic: "statistics",
    why: "The lasso; Elements of Statistical Learning." },
  { id: "hastie", name: "Trevor Hastie", affil: "Stanford", topic: "statistics",
    why: "ESL, GAMs, glmnet - the applied-statistics canon." },
  { id: "friedman", name: "Jerome Friedman", affil: "Stanford", topic: "statistics",
    why: "Gradient boosting, CART, ESL - the algorithmic side of the Stanford stats house." },
  { id: "breiman", name: "Leo Breiman", affil: "Berkeley (d. 2005)", topic: "statistics",
    why: "Random forests, CART, and 'Statistical Modeling: The Two Cultures' - the essay that named the split." },
  { id: "gelman", name: "Andrew Gelman", affil: "Columbia", topic: "statistics",
    why: "Bayesian Data Analysis, Stan, and the blog that keeps statistics honest." },
  { id: "wasserman", name: "Larry Wasserman", affil: "CMU", topic: "statistics",
    why: "All of Statistics - the bridge book between stats and ML. Mind-map page since the beginning." },
  { id: "shalizi", name: "Cosma Shalizi", affil: "CMU", topic: "statistics",
    why: "Statistics meets complexity; the notebooks/blog; power-law rigor with Clauset." },
  { id: "murphy", name: "Susan Murphy", affil: "Harvard", topic: "statistics",
    why: "Micro-randomized trials and adaptive interventions - RL meeting clinical statistics." },
  { id: "barber", name: "Rina Foygel Barber", affil: "UChicago", topic: "statistics",
    why: "Knockoffs with Candès; conformal - guarantees for selection." },

  { id: "vapnik", name: "Vladimir Vapnik", affil: "Columbia / AT&T lineage", topic: "learning-theory",
    why: "VC theory and SVMs - the theory the field stands on. Mind-map page since the beginning." },
  { id: "valiant", name: "Leslie Valiant", affil: "Harvard", topic: "learning-theory",
    why: "PAC learning - what 'learnable' means." },
  { id: "scholkopf", name: "Bernhard Schölkopf", affil: "MPI Tübingen", topic: "learning-theory",
    why: "Kernel methods, then causality - Learning with Kernels with Smola." },
  { id: "smola", name: "Alex Smola", affil: "Boson AI (ex-Amazon)", topic: "learning-theory",
    why: "Kernels at scale, then d2l.ai - theory that ships." },
  { id: "cortes", name: "Corinna Cortes", affil: "Google Research", topic: "learning-theory",
    why: "Support-Vector Networks (1995) with Vapnik - the SVM paper." },
  { id: "srebro", name: "Nathan Srebro", affil: "TTI-Chicago", topic: "learning-theory",
    why: "Matrix factorization, implicit bias of optimization - where learning theory meets training dynamics." },
  { id: "niyogi", name: "Partha Niyogi", affil: "UChicago (d. 2010)", topic: "learning-theory",
    why: "Manifold learning and the geometry of data." },
  { id: "mukherjee", name: "Sayan Mukherjee", affil: "Duke / MPI Leipzig", topic: "learning-theory",
    why: "Statistical learning meets topology and biology." },
  { id: "nowak", name: "Robert Nowak", affil: "Wisconsin", topic: "learning-theory",
    why: "Active learning and compressed sensing - the sampling side." },
  { id: "kondor", name: "Risi Kondor", affil: "UChicago", topic: "learning-theory",
    why: "Group-theoretic ML - symmetry before it was fashionable. Mind-map listing." },
  { id: "lim", name: "Lek-Heng Lim", affil: "UChicago", topic: "learning-theory",
    why: "Tensors and applied multilinear algebra." },
  { id: "mahoney", name: "Michael Mahoney", affil: "Berkeley ICSI", topic: "learning-theory",
    why: "Randomized numerical linear algebra; Hessian spectra of real networks - adjacent to the training-dynamics thread." },
  { id: "kolar", name: "Mladen Kolar", affil: "USC Marshall (ex-Booth)", topic: "learning-theory",
    why: "Graphical models and high-dim estimation. Mind-map listing." },
  { id: "weinberger", name: "Kilian Weinberger", affil: "Cornell", topic: "learning-theory",
    why: "Metric learning; the ML lectures John linked in the mind map." },
  { id: "guestrin", name: "Carlos Guestrin", affil: "Stanford", topic: "learning-theory",
    why: "XGBoost lineage, LIME - systems-minded ML. Mind-map page." },
  { id: "lafferty", name: "John Lafferty", affil: "Yale", topic: "learning-theory",
    why: "Conditional random fields with McCallum; stat-ML at the language boundary." },
  { id: "dwork", name: "Cynthia Dwork", affil: "Harvard", topic: "learning-theory",
    why: "Differential privacy - a definition that created a field." },

  { id: "pearl", name: "Judea Pearl", affil: "UCLA", topic: "probabilistic",
    why: "Bayes nets, then causality - do-calculus and the ladder." },
  { id: "koller", name: "Daphne Koller", affil: "insitro / Stanford", topic: "probabilistic",
    why: "Probabilistic graphical models; then Coursera; then biotech." },
  { id: "blei", name: "David Blei", affil: "Columbia", topic: "probabilistic",
    why: "LDA and variational inference - topic models as working machinery." },
  { id: "mackay", name: "David MacKay", affil: "Cambridge (d. 2016)", topic: "probabilistic",
    why: "Information Theory, Inference, and Learning Algorithms - the book. Also 'Sustainable Energy without the Hot Air.'" },
  { id: "mccallum", name: "Andrew McCallum", affil: "UMass Amherst", topic: "probabilistic",
    why: "CRFs, information extraction, OpenReview. Mind-map page." },

  { id: "hinton", name: "Geoffrey Hinton", affil: "Toronto / ex-Google", topic: "deep-learning",
    why: "Backprop era to deep learning era - the through-line." },
  { id: "lecun", name: "Yann LeCun", affil: "NYU / Meta", topic: "deep-learning",
    why: "Convnets from checks to everything." },
  { id: "bengio", name: "Yoshua Bengio", affil: "Mila", topic: "deep-learning",
    why: "Deep learning's third pillar; now safety." },
  { id: "schmidhuber", name: "Jürgen Schmidhuber", affil: "IDSIA / KAUST", topic: "deep-learning",
    why: "The LSTM lab and the long-memory of the field (as he will remind you)." },
  { id: "hopfield", name: "John Hopfield", affil: "Princeton", topic: "deep-learning",
    why: "Energy-based networks - physics entering neural computation; Nobel 2024." },
  { id: "goodfellow", name: "Ian Goodfellow", affil: "DeepMind lineage", topic: "deep-learning",
    why: "GANs; the Deep Learning textbook." },
  { id: "sutskever", name: "Ilya Sutskever", affil: "SSI (ex-OpenAI)", topic: "deep-learning",
    why: "AlexNet, seq2seq, GPT lineage - scaling as a worldview." },
  { id: "anandkumar", name: "Anima Anandkumar", affil: "Caltech", topic: "deep-learning",
    why: "Tensor methods; neural operators for scientific computing." },
  { id: "manning", name: "Christopher Manning", affil: "Stanford", topic: "deep-learning",
    why: "NLP from statistical to neural - CS224n as the field's front door." },
  { id: "girshick", name: "Ross Girshick", affil: "Meta AI lineage", topic: "deep-learning",
    why: "R-CNN line - detection as it became practical." },
  { id: "urtasun", name: "Raquel Urtasun", affil: "Waabi / Toronto", topic: "deep-learning",
    why: "Autonomous driving as an ML systems problem." },

  { id: "sutton", name: "Richard Sutton", affil: "Alberta", topic: "rl",
    why: "The RL book; The Bitter Lesson. Mind-map page since the beginning." },
  { id: "brunskill", name: "Emma Brunskill", affil: "Stanford", topic: "rl",
    why: "RL for education and people-facing decisions. Mind-map listing." },
  { id: "abbeel", name: "Pieter Abbeel", affil: "Berkeley", topic: "rl",
    why: "Deep RL for robotics; apprenticeship learning lineage." },
  { id: "hassabis", name: "Demis Hassabis", affil: "DeepMind", topic: "rl",
    why: "AlphaGo to AlphaFold - RL as an institution; Nobel 2024." },

  { id: "newell", name: "Allen Newell", affil: "CMU (d. 1992)", topic: "classic-ai",
    why: "Logic Theorist, SOAR, Human Problem Solving with Simon." },
  { id: "simon", name: "Herbert Simon", affil: "CMU (d. 2001)", topic: "classic-ai",
    why: "Bounded rationality - Nobel in economics, Turing Award in CS, one person." },
  { id: "minsky", name: "Marvin Minsky", affil: "MIT (d. 2016)", topic: "classic-ai",
    why: "Society of Mind; Perceptrons - both the vision and the winter." },
  { id: "russell", name: "Stuart Russell", affil: "Berkeley", topic: "classic-ai",
    why: "AIMA with Norvig; now provably-beneficial AI." },
  { id: "norvig", name: "Peter Norvig", affil: "Stanford HAI / ex-Google", topic: "classic-ai",
    why: "AIMA; 'The Unreasonable Effectiveness of Data'; pytudes." },
  { id: "mitchell", name: "Tom Mitchell", affil: "CMU", topic: "classic-ai",
    why: "THE Machine Learning textbook (1997); never-ending learning." },
  { id: "reddy", name: "Raj Reddy", affil: "CMU", topic: "classic-ai",
    why: "Speech recognition lineage; Turing 1994." },
  { id: "kanade", name: "Takeo Kanade", affil: "CMU", topic: "classic-ai",
    why: "Computer vision from Lucas-Kanade onward." },

  { id: "ritchie", name: "Dennis Ritchie", affil: "Bell Labs (d. 2011)", topic: "systems",
    why: "C and Unix - the substrate everything else runs on." },
  { id: "knuth", name: "Donald Knuth", affil: "Stanford", topic: "systems",
    why: "TAOCP, TeX - rigor as a way of life." },
  { id: "lamport", name: "Leslie Lamport", affil: "Microsoft Research", topic: "systems",
    why: "Distributed systems (Paxos, logical clocks) and LaTeX." },
  { id: "torvalds", name: "Linus Torvalds", affil: "Linux Foundation", topic: "systems",
    why: "Linux and git - infrastructure by force of will." },
  { id: "vanrossum", name: "Guido van Rossum", affil: "Python (ex-Microsoft)", topic: "systems",
    why: "Python - the language the whole field thinks in." },
  { id: "dean", name: "Jeff Dean", affil: "Google", topic: "systems",
    why: "MapReduce to TPUs - ML as a systems discipline." },
  { id: "stevens", name: "Rick Stevens", affil: "Argonne / UChicago", topic: "systems",
    why: "Exascale + AI for science; John's Argonne connection. Mind-map listing." },
  { id: "grossman", name: "Robert Grossman", affil: "UChicago", topic: "systems",
    why: "Data commons for science. Mind-map listing." },

  { id: "kleinberg", name: "Jon Kleinberg", affil: "Cornell", topic: "networks",
    why: "HITS, small-world navigation, algorithmic fairness. Mind-map listing." },
  { id: "leskovec", name: "Jure Leskovec", affil: "Stanford", topic: "networks",
    why: "SNAP, graph neural nets at scale, CS224W." },
  { id: "clauset", name: "Aaron Clauset", affil: "Colorado Boulder", topic: "networks",
    why: "Power-law rigor (with Shalizi); the structure of science itself." },
  { id: "cmoore", name: "Cristopher Moore", affil: "Santa Fe Institute", topic: "networks",
    why: "The Nature of Computation; phase transitions in inference." },
  { id: "strogatz", name: "Steven Strogatz", affil: "Cornell", topic: "networks",
    why: "Sync, small-world networks, Nonlinear Dynamics and Chaos - the dynamical-systems on-ramp. Mind-map listing." },
  { id: "erdos", name: "Paul Erdős", affil: "Itinerant (d. 1996)", topic: "networks",
    why: "Random graphs; the collaboration graph measures itself in his name." },

  { id: "oneil", name: "Cathy O'Neil", affil: "ORCAA", topic: "society",
    why: "Weapons of Math Destruction - accountability before it was a beat." },
  { id: "gebru", name: "Timnit Gebru", affil: "DAIR", topic: "society",
    why: "Datasheets, Stochastic Parrots, DAIR - the cost of saying it early. Mind-map listing." },
  { id: "abebe", name: "Rediet Abebe", affil: "Berkeley", topic: "society",
    why: "Algorithms and social change; MD4SG." },

  { id: "bach", name: "Francis Bach", affil: "INRIA", topic: "convex-control",
    why: "Stochastic approximation and kernels - optimization for ML with proofs." },
  { id: "swright", name: "Stephen Wright", affil: "Wisconsin", topic: "convex-control",
    why: "Numerical Optimization (with Nocedal) - the working optimizer's reference." },
  { id: "mallat", name: "Stéphane Mallat", affil: "Collège de France", topic: "highdim",
    why: "Wavelets and scattering transforms - structure before learning." },
  { id: "tengyuma", name: "Tengyu Ma", affil: "Stanford", topic: "learning-theory",
    why: "Non-convex optimization theory into the LLM era." },
  { id: "blum", name: "Avrim Blum", affil: "TTI-Chicago", topic: "learning-theory",
    why: "Learning theory canon - online learning, semi-supervised." },
  { id: "rudin", name: "Cynthia Rudin", affil: "Duke", topic: "learning-theory",
    why: "Stop explaining black boxes - build interpretable models instead." },
  { id: "rtibshirani", name: "Ryan Tibshirani", affil: "Berkeley", topic: "statistics",
    why: "Conformal prediction, trend filtering. (Yes - Rob's son; both on the map.)" },
  { id: "diaconis", name: "Persi Diaconis", affil: "Stanford", topic: "statistics",
    why: "Probability with showmanship - shuffles, coincidences, MCMC mixing." },
  { id: "bishop", name: "Christopher Bishop", affil: "Microsoft Research", topic: "probabilistic",
    why: "PRML - the pattern-recognition text of a generation." },
  { id: "kmurphy", name: "Kevin Murphy", affil: "Google", topic: "probabilistic",
    why: "The Probabilistic Machine Learning volumes - the field, organized." },
  { id: "karpathy", name: "Andrej Karpathy", affil: "ex-OpenAI / Tesla", topic: "deep-learning",
    why: "nanoGPT and the zero-to-hero lectures - teaching by building in public." },
  { id: "ng", name: "Andrew Ng", affil: "Stanford / DeepLearning.AI", topic: "deep-learning",
    why: "Coursera-era ML teaching at scale; John taught for DeepLearning.AI." },
  { id: "efros", name: "Alexei Efros", affil: "Berkeley", topic: "deep-learning",
    why: "Self-supervision and the unreasonable effectiveness of data + nearest neighbors." },
  { id: "levine", name: "Sergey Levine", affil: "Berkeley", topic: "rl",
    why: "Deep RL for robotics - the empirical program." },
  { id: "amodei", name: "Dario Amodei", affil: "Anthropic", topic: "deep-learning",
    why: "Scaling laws lineage + safety as strategy." },
  { id: "bender", name: "Emily Bender", affil: "UW", topic: "deep-learning",
    why: "Linguistic discipline for NLP; Stochastic Parrots." },
  { id: "neubig", name: "Graham Neubig", affil: "CMU", topic: "deep-learning",
    why: "MT and code generation; teaching materials that travel." },
  { id: "hofstadter", name: "Douglas Hofstadter", affil: "Indiana", topic: "classic-ai",
    why: "GEB; analogy as the core of cognition - Copycat with Melanie Mitchell." },
  { id: "papert", name: "Seymour Papert", affil: "MIT (d. 2016)", topic: "hci",
    why: "Logo and constructionism - Mindstorms; also Perceptrons with Minsky. The teaching-by-building ancestor." },
  { id: "chollet", name: "François Chollet", affil: "ex-Google", topic: "systems",
    why: "Keras; ARC and On the Measure of Intelligence - tools plus a thesis." },
  { id: "foster", name: "Ian Foster", affil: "Argonne / UChicago", topic: "systems",
    why: "Grid computing, Globus - John's Argonne orbit." },
  { id: "barabasi", name: "Albert-László Barabási", affil: "Northeastern", topic: "networks",
    why: "Scale-free networks - preferential attachment as a worldview." },
  { id: "melmitchell", name: "Melanie Mitchell", affil: "Santa Fe Institute", topic: "networks",
    why: "Complexity; AI skepticism done right; Copycat with Hofstadter." },
  { id: "margmitchell", name: "Margaret Mitchell", affil: "Hugging Face", topic: "society",
    why: "Model cards; Stochastic Parrots co-author." },
  { id: "whittaker", name: "Meredith Whittaker", affil: "Signal", topic: "society",
    why: "AI Now co-founder; privacy as infrastructure." },
  { id: "aaronson", name: "Scott Aaronson", affil: "UT Austin", topic: "math",
    why: "Quantum complexity; Shtetl-Optimized - thinking in public." },
  { id: "conway", name: "John Conway", affil: "Princeton (d. 2020)", topic: "math",
    why: "Life, surreal numbers - play as mathematics." },
  { id: "strang", name: "Gilbert Strang", affil: "MIT", topic: "math",
    why: "Linear algebra taught to the world - 18.06 as a public good." },
  { id: "gowers", name: "Timothy Gowers", affil: "Cambridge", topic: "math",
    why: "Polymath projects - massively collaborative mathematics; exposition as craft." },
  { id: "villani", name: "Cédric Villani", affil: "Lyon", topic: "math",
    why: "Optimal transport - the math under Wasserstein distances." },

  { id: "dey", name: "Anind Dey", affil: "UW iSchool (dean; CMU HCII lineage)", topic: "hci",
    why: "Context-aware computing - the sensing-the-human thread." },
  { id: "forlizzi", name: "Jodi Forlizzi", affil: "CMU HCII", topic: "hci",
    why: "Design research; service design for AI systems." },
  { id: "harrison", name: "Chris Harrison", affil: "CMU HCII", topic: "hci",
    why: "Future Interfaces Group - novel sensing and input; the maker end of HCI." },
  { id: "jwiese", name: "Jason Wiese", affil: "Utah (CMU HCII PhD)", topic: "hci",
    why: "Personal data and health informatics." },
  { id: "ewiese", name: "Eliane Stampfer Wiese", affil: "Utah (CMU HCII PhD)", topic: "hci",
    why: "Learning science and CS education - what makes feedback actually teach." },
  { id: "nbrown", name: "Noelle Brown", affil: "Utah (PhD student, Wiese lab)", topic: "hci",
    why: "Ethics in computing education - responsible computing woven into assignments." },

  { id: "winograd", name: "Terry Winograd", affil: "Stanford", topic: "hci",
    why: "From SHRDLU to HCI - Understanding Computers and Cognition; Page's advisor." },
  { id: "hong", name: "Jason Hong", affil: "CMU HCII", topic: "hci",
    why: "Privacy and mobile security from the human side." },
  { id: "zimmerman", name: "John Zimmerman", affil: "CMU HCII", topic: "hci",
    why: "Research through design; the Forlizzi pairing." },
  { id: "kittur", name: "Aniket Kittur", affil: "CMU HCII", topic: "hci",
    why: "Crowdsourcing and sensemaking at scale." },
  { id: "koedinger", name: "Ken Koedinger", affil: "CMU HCII", topic: "hci",
    why: "Intelligent tutoring - the learning-science anchor; Eliane's intellectual home." },
  { id: "ogan", name: "Amy Ogan", affil: "CMU HCII", topic: "hci",
    why: "Culturally-aware learning technology." },
  { id: "rose", name: "Carolyn Rosé", affil: "CMU HCII/LTI", topic: "hci",
    why: "Discourse analysis in learning - language as the learning signal." },
  { id: "hudson", name: "Scott Hudson", affil: "CMU HCII", topic: "hci",
    why: "UI technology and fabrication - the maker end, like Harrison." },
  { id: "bigham", name: "Jeff Bigham", affil: "CMU HCII", topic: "hci",
    why: "Accessibility + human computation (VizWiz)." },
  { id: "myers", name: "Brad Myers", affil: "CMU HCII", topic: "hci",
    why: "Programming-by-demonstration, end-user programming." },
  { id: "kiesler", name: "Sara Kiesler", affil: "CMU HCII", topic: "hci",
    why: "Social psychology of computing - founder generation." },
  { id: "kraut", name: "Robert Kraut", affil: "CMU HCII", topic: "hci",
    why: "Online communities; Internet Paradox with Kiesler." },
  { id: "morris", name: "Meredith Ringel Morris", affil: "Google DeepMind", topic: "hci",
    why: "Human-AI interaction; accessibility; defined the AGI-levels framing." },

  { id: "babai", name: "László Babai", affil: "UChicago", topic: "math",
    why: "Graph isomorphism in quasipolynomial time - the department's giant." },
  { id: "amit", name: "Yali Amit", affil: "UChicago Statistics", topic: "statistics",
    why: "Statistics and vision; the Amit-Geman randomized-trees lineage that fed random forests." },
  { id: "kurtz", name: "Stuart Kurtz", affil: "UChicago", topic: "math",
    why: "Computability and complexity - the theory old guard of John's department." },
  { id: "jsimon", name: "Janos Simon", affil: "UChicago", topic: "math",
    why: "Complexity theory - the department's long memory." },
  { id: "mulmuley", name: "Ketan Mulmuley", affil: "UChicago", topic: "math",
    why: "Geometric complexity theory - the long program on P vs NP." },
  { id: "mcallester", name: "David McAllester", affil: "TTIC", topic: "learning-theory",
    why: "PAC-Bayes, then deep learning theory - TTIC's founding intellect." },
  { id: "livescu", name: "Karen Livescu", affil: "TTIC", topic: "deep-learning",
    why: "Speech and representation learning." },
  { id: "shakhnarovich", name: "Greg Shakhnarovich", affil: "TTIC", topic: "deep-learning",
    why: "Vision and learned representations." },
  { id: "chien", name: "Andrew Chien", affil: "UChicago", topic: "systems",
    why: "Large-scale systems; computing's carbon footprint." },
  { id: "hoffmann", name: "Hank Hoffmann", affil: "UChicago", topic: "systems",
    why: "Self-aware computing - systems that regulate themselves (control theory in the machine room)." },

  { id: "canziani", name: "Alfredo Canziani", affil: "NYU", topic: "educators",
    why: "Deep learning lectures with LeCun - teaching as craft. Mind-map link." },
  { id: "kilcher", name: "Yannic Kilcher", affil: "YouTube / OpenAssistant", topic: "educators",
    why: "Paper explanations at the speed the field moves. Mind-map link." },
  { id: "rosenberg", name: "David S. Rosenberg", affil: "Bloomberg", topic: "educators",
    why: "Foundations of Machine Learning course John bookmarked in the mind map." },
];

const PAPERS = [
  { title: "A Differential Equation for Modeling Nesterov's Accelerated Gradient Method", year: 2016,
    venue: "JMLR", link: "https://arxiv.org/abs/1503.01243", authors: ["su", "boyd", "candes"],
    note: "The optimizer-as-ODE landmark." },
  { title: "Analysis and Design of Optimization Algorithms via Integral Quadratic Constraints", year: 2016,
    venue: "SIAM J. Optim.", link: "https://arxiv.org/abs/1408.3595", authors: ["lessard", "recht", "packard"],
    note: "The landmark: optimizers as robust control." },
  { title: "A Lyapunov Analysis of Momentum Methods in Optimization", year: 2021,
    venue: "JMLR", link: "https://arxiv.org/abs/1611.02635", authors: ["wilson", "recht", "jordan"] },
  { title: "A Variational Perspective on Accelerated Methods in Optimization", year: 2016,
    venue: "PNAS", link: "https://arxiv.org/abs/1603.04245", authors: ["wibisono", "wilson", "jordan"] },
  { title: "Exact Matrix Completion via Convex Optimization", year: 2008,
    venue: "Found. Comput. Math.", link: "https://arxiv.org/abs/0805.4471", authors: ["candes", "recht"] },
  { title: "Robust Uncertainty Principles (compressed sensing)", year: 2006,
    venue: "IEEE Trans. IT", link: "https://arxiv.org/abs/math/0409186", authors: ["candes", "tao"],
    note: "With Justin Romberg." },
  { title: "Gradient Descent on Neural Networks Typically Occurs at the Edge of Stability", year: 2021,
    venue: "ICLR", link: "https://arxiv.org/abs/2103.00065", authors: ["cohen", "kolter", "talwalkar"],
    note: "With Simran Kaur and Yuanzhi Li." },
  { title: "Convex Optimization (the book)", year: 2004,
    venue: "Cambridge", link: "https://web.stanford.edu/~boyd/cvxbook/", authors: ["boyd"],
    note: "With Lieven Vandenberghe." },
  { title: "Cyclical Learning Rates for Training Neural Networks", year: 2017,
    venue: "WACV", link: "https://arxiv.org/abs/1506.01186", authors: ["smith"],
    note: "Plus the LR range test and super-convergence (arXiv:1708.07120)." },

  { title: "The Elements of Statistical Learning", year: 2009,
    venue: "Springer (2nd ed.)", link: "https://hastie.su.domains/ElemStatLearn/", authors: ["hastie", "tibshirani", "friedman"] },
  { title: "Classification and Regression Trees (CART)", year: 1984,
    venue: "Wadsworth", link: "https://doi.org/10.1201/9781315139470", authors: ["breiman", "friedman"],
    note: "With Olshen and Stone." },
  { title: "Computer Age Statistical Inference", year: 2016,
    venue: "Cambridge", link: "https://hastie.su.domains/CASI/", authors: ["efron", "hastie"] },
  { title: "Random Forests", year: 2001,
    venue: "Machine Learning", link: "https://doi.org/10.1023/A:1010933404324", authors: ["breiman"] },
  { title: "Support-Vector Networks", year: 1995,
    venue: "Machine Learning", link: "https://doi.org/10.1007/BF00994018", authors: ["cortes", "vapnik"] },
  { title: "Learning with Kernels", year: 2002,
    venue: "MIT Press", link: "https://mitpress.mit.edu/9780262536578/", authors: ["scholkopf", "smola"] },
  { title: "Conditional Random Fields", year: 2001,
    venue: "ICML", link: "https://dl.acm.org/doi/10.5555/645530.655813", authors: ["lafferty", "mccallum"],
    note: "With Fernando Pereira." },
  { title: "Latent Dirichlet Allocation", year: 2003,
    venue: "JMLR", link: "https://jmlr.org/papers/v3/blei03a.html", authors: ["blei", "jordan", "ng"] },
  { title: "Controlling the False Discovery Rate via Knockoffs", year: 2015,
    venue: "Annals of Statistics", link: "https://arxiv.org/abs/1404.5609", authors: ["barber", "candes"] },
  { title: "Curvelets - a Surprisingly Effective Nonadaptive Representation", year: 2000,
    venue: "Curves & Surfaces", link: "https://statweb.stanford.edu/~candes/publications.html", authors: ["candes", "donoho"] },
  { title: "Deep Learning (the review)", year: 2015,
    venue: "Nature", link: "https://doi.org/10.1038/nature14539", authors: ["lecun", "bengio", "hinton"] },
  { title: "ImageNet Classification with Deep CNNs (AlexNet)", year: 2012,
    venue: "NeurIPS", link: "https://dl.acm.org/doi/10.1145/3065386", authors: ["sutskever", "hinton"],
    note: "With Alex Krizhevsky." },
  { title: "Generative Adversarial Nets", year: 2014,
    venue: "NeurIPS", link: "https://arxiv.org/abs/1406.2661", authors: ["goodfellow", "bengio"],
    note: "With Mirza, Xu, Warde-Farley, Ozair, Courville." },
  { title: "Artificial Intelligence: A Modern Approach", year: 1995,
    venue: "Pearson (4 eds.)", link: "https://aima.cs.berkeley.edu/", authors: ["russell", "norvig"] },
  { title: "Human Problem Solving", year: 1972,
    venue: "Prentice-Hall", link: "https://psycnet.apa.org/record/1973-10478-000", authors: ["newell", "simon"] },
  { title: "Power-Law Distributions in Empirical Data", year: 2009,
    venue: "SIAM Review", link: "https://arxiv.org/abs/0706.1062", authors: ["clauset", "shalizi"],
    note: "With Mark Newman." },
  { title: "Graphs over Time: Densification Laws", year: 2005,
    venue: "KDD", link: "https://doi.org/10.1145/1081870.1081893", authors: ["leskovec", "kleinberg"],
    note: "With Christos Faloutsos." },
  { title: "Roles for Computing in Social Change", year: 2020,
    venue: "FAccT", link: "https://arxiv.org/abs/1912.04883", authors: ["abebe", "kleinberg"],
    note: "With Barocas, Levy, Raghavan, Robinson." },
  { title: "Reinforcement Learning: An Introduction", year: 2018,
    venue: "MIT Press (2nd ed.)", link: "http://incompleteideas.net/book/the-book.html", authors: ["sutton"],
    note: "With Andrew Barto." },
  { title: "Causality: Models, Reasoning, and Inference", year: 2000,
    venue: "Cambridge", link: "http://bayes.cs.ucla.edu/BOOK-2K/", authors: ["pearl"] },

  { title: "Perceptrons", year: 1969,
    venue: "MIT Press", link: "https://mitpress.mit.edu/9780262630221/", authors: ["minsky", "papert"],
    note: "The book that named the limits - and the winter." },
  { title: "On Discriminative vs. Generative Classifiers", year: 2001,
    venue: "NeurIPS", link: "https://papers.nips.cc/paper/2020-on-discriminative-vs-generative-classifiers", authors: ["ng", "jordan"] },
  { title: "Kernel Independent Component Analysis", year: 2002,
    venue: "JMLR", link: "https://jmlr.org/papers/v3/bach02a.html", authors: ["bach", "jordan"] },
  { title: "End-to-End Training of Deep Visuomotor Policies", year: 2016,
    venue: "JMLR", link: "https://arxiv.org/abs/1504.00702", authors: ["levine", "abbeel"],
    note: "With Chelsea Finn and Trevor Darrell." },
  { title: "On the Dangers of Stochastic Parrots", year: 2021,
    venue: "FAccT", link: "https://dl.acm.org/doi/10.1145/3442188.3445922", authors: ["bender", "gebru", "margmitchell"],
    note: "With Angelina McMillan-Major." },
  { title: "The Copycat Project: Analogy-Making as Perception", year: 1988,
    venue: "AAAI / book chapters", link: "https://melaniemitchell.me/", authors: ["hofstadter", "melmitchell"] },
  { title: "Emergence of Scaling in Random Networks", year: 1999,
    venue: "Science", link: "https://arxiv.org/abs/cond-mat/9910332", authors: ["barabasi"],
    note: "With Réka Albert." },
  { title: "On the Measure of Intelligence", year: 2019,
    venue: "arXiv", link: "https://arxiv.org/abs/1911.01547", authors: ["chollet"] },
  { title: "Stop Explaining Black Box Models for High Stakes Decisions", year: 2019,
    venue: "Nature MI", link: "https://arxiv.org/abs/1811.10154", authors: ["rudin"] },
  { title: "Research through Design as a Method for Interaction Design Research in HCI", year: 2007,
    venue: "CHI", link: "https://doi.org/10.1145/1240624.1240704", authors: ["zimmerman", "forlizzi"],
    note: "With Shelley Evenson." },
  { title: "Internet Paradox: Social Involvement and Well-Being", year: 1998,
    venue: "American Psychologist", link: "https://doi.org/10.1037/0003-066X.53.9.1017", authors: ["kraut", "kiesler"],
    note: "With Patterson, Lundmark, Mukopadhyay, Scherlis." },

  { title: "Rodeo: Sparse, Greedy Nonparametric Regression", year: 2008,
    venue: "Annals of Statistics", link: "https://arxiv.org/abs/0803.1709", authors: ["wasserman", "lafferty"] },
  { title: "Computer-Intensive Methods in Statistics", year: 1983,
    venue: "Scientific American", link: "https://doi.org/10.1038/scientificamerican0583-116", authors: ["diaconis", "efron"] },
  { title: "Large Scale Distributed Deep Networks", year: 2012,
    venue: "NeurIPS", link: "https://papers.nips.cc/paper/4687-large-scale-distributed-deep-networks", authors: ["dean", "ng"],
    note: "With Corrado, Monga, Chen, Devin, Le, and others." },
  { title: "Efficient Solution Algorithms for Factored MDPs", year: 2003,
    venue: "JAIR", link: "https://doi.org/10.1613/jair.1000", authors: ["guestrin", "koller"],
    note: "With Parr and Venkataraman; Guestrin was Koller's student." },
  { title: "Harnessing the Wisdom of Crowds in Wikipedia", year: 2008,
    venue: "CSCW", link: "https://doi.org/10.1145/1460563.1460572", authors: ["kittur", "kraut"] },
  { title: "TapSense: Enhancing Finger Interaction on Touch Surfaces", year: 2011,
    venue: "UIST", link: "https://doi.org/10.1145/2047196.2047279", authors: ["harrison", "hudson"],
    note: "With Julia Schwarz; Hudson was Harrison's advisor." },
  { title: "Designing Grounded Feedback in Interactive Tutors", year: 2017,
    venue: "IJAIED", link: "https://doi.org/10.1007/s40593-016-0125-9", authors: ["ewiese", "koedinger"],
    note: "Koedinger was Wiese's PhD advisor." },
  { title: "A Bias Correction for the Minimum Error Rate in Cross-Validation", year: 2009,
    venue: "Annals of Applied Statistics", link: "https://arxiv.org/abs/0908.2904", authors: ["rtibshirani", "tibshirani"],
    note: "Father and son." },
];
